# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/sources_1/imports/Source/gesture_detect.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/sources_1/imports/Source/serial_send.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/sources_1/imports/Source/image_process.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/Source/mem_modules.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/Source/FT2232_Data.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/sources_1/imports/Source/display_8hex.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/sources_1/imports/Source/debounce.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/sources_1/new/TP_Top.v
  /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/sources_1/imports/Source/send_mouse.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/constrs_1/imports/Source/Nexys4DDR_Master_lab4.xdc
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/a/d/adcheng/Documents/6.111/Project/FT2232H/FT2232H/FT2232H.srcs/constrs_1/imports/Source/Nexys4DDR_Master_lab4.xdc]


synth_design -top TP_Top -part xc7a100tcsg324-3


write_checkpoint -force -noxdef TP_Top.dcp

catch { report_utilization -file TP_Top_utilization_synth.rpt -pb TP_Top_utilization_synth.pb }
